### ISSUE TITLE
Feature Request: wrap etcd integration in a more official manner

### ISSUE THREAD

**Issue by DreadPirateShawn** [projectcalico/bird#20]
Currently the docs https://github.com/projectcalico/calico-bird/blob/ea2df315f69a5d636b3e62fdcf7650963b1c77e1/build_routereflector/README.md include a step to execute a curl PUT against etcd, to add an entry for the route reflector.

It seems like this should be handled more officially -- perhaps via add/remove commands to calicoctl, eg:

```
calicoctl rr add <IPv4_RR> as <CLUSTER_ID>
calicoctl rr remove <IPv4_RR> as <CLUSTER_ID>
calicoctl rr show
```

(In my opinion, this seems preferable over having the calico/routereflector image create the entry automatically, since that leaves the risk of a crashed / forcibly stopped container resulting in orphan entries.)

**Comment by robbrockbank** [comment]
@DreadPirateShawn :  The RR container image is somewhat experimental in the sense that it has some limitations that will make it difficult to use in a real deployment - however, it is now more formally documented in our docs: 

http://docs.projectcalico.org/master/usage/routereflector/calico-routereflector

Moving forward, I'd like to productize this more - and adding `calicoctl` support is on my radar.  I suspect though that we'd end up using a slightly different configuration model that uses labels to handle automatic peerings ... the upshot is there is some significant design thinking to be done before we do that.  I can't currently give a timeframe for that I'm afraid.

**Comment by caseydavenport** [comment]
Closing this since v3 doesn't use etcdctl.
