### ISSUE TITLE
BIRD ignores route updates during a poll

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/bird#9]
Noticed during my scale testing work.  It appears that BIRD misses route updates that occur during its periodic kernel scan.

Symptom is that TTFP in the container test is either very fast or cluster around the polling interval.  Changing the scan interval changes the position of the TTFP cluster.

Ideally, we'd go the whole hog and handle adds and deletes with netlink events so that polling is never needed (or is used only for occasional "repair").

**Comment by fasaxc** [comment]
According to the upstream developer, it can also miss updates whenever it is doing a write to the dataplane too.

**Comment by rafaelvanoni** [comment]
@neiljerram Similar to http://github.com/projectcalico/felix/issues/625, could you add an update or close one of them as dup?

**Comment by nelljerram** [comment]
@rafaelvanoni I don't think we should think of these as dupes, because they affect different components.  Also, has it been demonstrated that the underlying causes are the same?  (I don't think so.)

**Comment by fasaxc** [comment]
Maybe we should just close this?  AFAIK, it's still the case but we reduced its impact by implementing IPAM aggregation (so route changes are super rare in a calico-ipam based cluster).

**Comment by nelljerram** [comment]
For the record,

- Is this about 'updates' meaning routes that have been added to the local kernel (e.g. by Felix) or 'updates' meaning information received from other BGP speakers?

- If it's the former, is the miss recovered, and if so when?  Perhaps at the end of the current scan period, or at the end of the next scan period?

**Comment by fasaxc** [comment]
It's updates added to the kernel.  IIRC, BIRD turns off is event watch so it can re-use the same netlink socket for scanning/making changes.

**Comment by nelljerram** [comment]
OK, thanks.  So presumably then any missed route changes are picked up on the next poll, which means after another 2 seconds (https://github.com/projectcalico/confd/blob/master/etc/calico/confd/templates/bird.cfg.template#L41).

I think we're OK to close this, then.
